### ISSUE TITLE
Increasing max texture/image size

### ISSUE THREAD

**Issue by andyzaharia** [consbio/mbgl-renderer#46]
First of all thank you for this awesome tool! :)

I'm having a bit of a dilemma here, I'm trying to create an image that is bigger than the default 8192x8192 size that I get when testing on Ubuntu. I did a bit of research and it seems to be related to the xvfb tool. I looked into changing the xvfb settings and there doesnt seem to be clear way of tweaking  the xvfb to allow creating bigger textures. On my macbook I was able to generate an image that is 11000x11000 pixels which makes me wonder if its xvfb related... 

Is it possible to actually create an image that will be lets say 10000x1000 pixels? 

Thanks a lot!

**Comment by brendan-ward** [comment]
@andyzaharia  see related issue in mapbox-gl: https://github.com/mapbox/mapbox-gl-native/issues/5184
You probably already saw: https://stackoverflow.com/questions/40645132/how-to-increase-gl-max-texture-size-for-mesa-drivers

From within our docker container:
```
root@fe51a49379ae:/app# glxinfo -l | grep GL_MAX_TEXTURE_SIZE
    GL_MAX_TEXTURE_SIZE = 8192
```

Outside docker, on a Mac, I am also able to generate a 10000 x 10000 pixel image.  I agree with your conclusion, this is due to Xvfb.

When I request 10000 x 10000 pixel images from our docker container, it crashes the server process in the container.

Just like you found, changing the screen dimensions provided to Xvfb to be greater than your maximum requested size does not resolve the error.  I also don't see any configuration options we can provide to the GL setup to use a higher max texture.

My recommendation echoes that on the mapbox-gl post above: create smaller images and merge them together outside `mbgl-renderer`.

If you do find a solution that lets you use resolutions larger than 8192x8192, please let us know!
