### ISSUE TITLE
Issue with adding symbols from geojson

### ISSUE THREAD

**Issue by kjkurtz** [consbio/mbgl-renderer#63]
I've been experiencing an odd issue with adding a symbol layer from a geojson source. The geojson is a FeatureCollection of lines (I've included the geojson in the jsfiddle example below). The exact style works just fine in that jsfiddle with vanilla MapboxGLJS. Once I try to add that same layer to the map via mbgl-renderer, I get `Error rendering map [Error: Invalid URI "/"]` Any ideas what I may be doing wrong? Thanks!

Working example with vanilla Mapbox GL JS including the geojson in question: https://jsfiddle.net/kjkurtz/ytLkauwo/

mgbl-renderer version: 0.7.1
Environment: Node 10.22.0

**Comment by brendan-ward** [comment]
@kjkurtz can you please also share the style JSON you are passing as input to `mbgl-renderer`?  Your working example above uses the Mapbox GL JS API to add a source then add a layer; all of this is encapsulated into a single style JSON ([example](https://github.com/consbio/mbgl-renderer/blob/master/tests/fixtures/example-style-geojson.json)).

You can use that same JSON to create your map in Mapbox GL JS to test that it works properly there; instead of a named style hosted by Mapbox, you pass in the json to the `style` parameter when constructing the map object.

**Comment by kjkurtz** [comment]
What do you know?! That was the ticket to a more verbose error message I could take action on.
`Error: layers[3].layout.text-field: use of "text-field" requires a style "glyphs" property`
All I had to do was add a source for the 'glyphs' and everything started working.

Thanks so much for the insight!

**Comment by samuel-litzler** [comment]
Hi,
Same issue here, but now we need access token.

i have three sources : mapbox satellite, geojson polygon, geojson centroid of polygon.

If i use the glyphs i have this error : 
![image](https://user-images.githubusercontent.com/24872653/155697993-ac33a302-ebe9-4c8f-a72e-eb9a0e2e13c9.png)

Here this is the source of mapbox satellite : 
![image](https://user-images.githubusercontent.com/24872653/155698226-7552e6c5-3dcd-42f5-8e66-b9fdd59eabe9.png)

I create the source with https : 
```
"mapbox": {
      "type": "raster",
      "url": "https://api.mapbox.com/v4/mapbox.satellite.json?secure=trueaccess_token=my token",
      "tileSize": 256
    },
 ```
 So the glyphs as well with http (otherwise i have "access_token missing" error):
 `  "glyphs": "https://api.mapbox.com/fonts/v1/mapbox/{fontstack}/{range}.pbf?secure=true&access_token=my token",
 `
