### ISSUE TITLE
Attribution is not getting displayed in static map images

### ISSUE THREAD

**Issue by neelakandan-dhanigachalam** [consbio/mbgl-renderer#84]
Hi,

I'm using the docker based mbgl-renderer. The mbtiles sources has attribution built in. When we generate the static image, the attribution is not getting generated. Even I tried to add the attribution in vector sources in styles. Still it is not getting generated in static maps.
Am I missing anything here? Also, tried to pass the images parameters. But I'm not able to send images parameters, since there is no configuration structure specified. 
Can you please help on this?

**Comment by brendan-ward** [comment]
Attribution is a client-side problem; we don't embed attribution into the images and don't intend to - this library just renders map images.  As a user of a library, you're responsible for doing that in the way that is best for how you are specifically using the images.  In most of my use cases, where we render map images into PDF, I put the attribution in text below the image rather than rendering the text to pixels then embedding into the map image.

For `images` documentation, please see the structure at the bottom of the [NodeJS API](https://github.com/consbio/mbgl-renderer#nodejs-api) in the README; this is the structure.  If you are using `mbgl-renderer` as a server, then `images` is a query (GET) or body (POST) parameter with a URL encoded JSON value.  Apologies for the poor documentation, `images` support is very new.  If you encounter issues using `images`, please add a new issue for that.

**Comment by neelakandan-dhanigachalam** [comment]
Understood Brendan. Thanks for your immediate response. I'll check the images documentation and update you if any issues.
